services:
  db:
    image: postgres:15
    container_name: sneaker-bureau-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1029384756
      POSTGRES_DB: sneaker_bureau
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: sneaker-bureau-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: "postgresql+asyncpg://user:1029384756@db:5432/sneaker_bureau"
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
